import type { Capability, RaciTeam } from "./types"

export const raciTeams: RaciTeam[] = [
  "Owner Strat",
  "Owner Team",
  "UIF",
  "Hubs",
  "Procore Connect",
  "Assist",
  "Tool Teams",
]

const PROTOTYPE_URL =
  "https://www.figma.com/proto/gCB2fsazmfz1ysYaoobFYV/Owner-Strategy---Concept-Work?page-id=1131%3A548890&node-id=1920-298256&p=f&viewport=269%2C80%2C0.38&t=nUrT4JJGJJviwWgF-8&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=1920%3A298256&hide-ui=1"

const FIGMA_URL =
  "https://www.figma.com/design/Mg4ZHWuogP7i8nD91a9Z9i/Ideal-Owners-Experience?node-id=1-2&t=kvUVrb6qCkrjRLpq-1"

const IMAGES = {
  healthAndRisk: "/images/healthandrisk.png",
  ownerHubs: "/images/ownershubs.png",
  navigationIA: "/images/navigation-ia.png",
  interactionModel: "/images/interactionmodel.png",
  aiSummary: "/images/aisummary.png",
  aiAssist: "/images/aiassist.png",
  stageBasedWorkflows: "/images/stage-based-workflows.png",
  procoreConnect: "/images/procore-connect-for-owners.png",
  ucCompare: "/images/uc-compare.png",
  portfolioViews: "/images/portfolio-views.png",
  pageLevelFiltering: "/images/page-level-filtering.png",
  ucViewModes: "/images/uc-view-modes.png",
}

export const initialCapabilities: Capability[] = [
  {
    id: "1",
    name: "Health & Risk Framework",
    description: "Unified framework for tracking project health and identifying risks across the portfolio",
    ownerValue: "High",
    platformReadiness: "High",
    businessValue: "High",
    dependencies: "Low",
    dependencyTeams: ["Platform", "Hubs"],
    tier: "Net New",
    risks: ["Data integration complexity", "Cross-team alignment needed"],
    assumptions: ["Existing data sources are reliable", "Teams can agree on health metrics"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "I",
      Hubs: "C",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-02-01",
      endDate: "2026-06-30",
      status: "Not Started",
    },
    levelOfEffort: "Large",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.s8gh2dh8bldz#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.healthAndRisk,
  },
  {
    id: "2",
    name: "Owners Hubs",
    description: "Centralized hub experience for owners to manage their portfolio and projects",
    ownerValue: "High",
    platformReadiness: "High",
    businessValue: "Medium",
    dependencies: "Medium",
    dependencyTeams: ["Hubs", "UIF"],
    tier: "Extension",
    risks: ["Scope creep potential", "Performance at scale"],
    assumptions: ["Clear owner persona definition", "Hub architecture supports customization"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "I",
      Hubs: "C",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "C",
    },
    timeline: {
      startDate: "2026-01-15",
      endDate: "2026-05-31",
      status: "Not Started",
    },
    levelOfEffort: "Medium",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.q3q39yaxwtqf#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.ownerHubs,
  },
  {
    id: "3",
    name: "Page-level Filtering",
    description: "Consistent filtering experience across all pages with saved filter presets",
    ownerValue: "Medium",
    platformReadiness: "High",
    businessValue: "Low",
    dependencies: "Medium",
    dependencyTeams: ["UIF"],
    tier: "Net New",
    risks: ["Inconsistent implementation across tools"],
    assumptions: ["UIF components are mature enough"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "C",
      Hubs: "C",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-03-01",
      endDate: "2026-05-15",
      status: "Not Started",
    },
    levelOfEffort: "Medium",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.d4ape3z40tvx#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.pageLevelFiltering,
  },
  {
    id: "4",
    name: "Navigation/IA Update",
    description: "Restructured information architecture optimized for owner workflows",
    ownerValue: "Medium",
    platformReadiness: "Medium",
    businessValue: "Low",
    dependencies: "High",
    dependencyTeams: ["UIF", "Platform", "Hubs"],
    tier: "Enhancement",
    risks: ["User adoption challenges", "Breaking existing workflows"],
    assumptions: ["Research validates new IA structure", "Phased rollout possible"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "C",
      UIF: "R",
      Hubs: null,
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-04-01",
      endDate: "2026-09-30",
      status: "Not Started",
    },
    levelOfEffort: "Large",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.mruzz08uym01#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.navigationIA,
  },
  {
    id: "5",
    name: "Portfolio Views",
    description: "Multi-project views with aggregated metrics and comparison capabilities",
    ownerValue: "Medium",
    platformReadiness: "High",
    businessValue: "Medium",
    dependencies: "High",
    dependencyTeams: ["Platform", "Hubs", "Connect"],
    tier: "Net New",
    risks: ["Data aggregation complexity", "Performance concerns"],
    assumptions: ["Cross-project data model exists", "Permissions can be managed at portfolio level"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "C",
      UIF: "C",
      Hubs: "C",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "R",
    },
    timeline: {
      startDate: "2026-06-01",
      endDate: "2026-12-31",
      status: "Not Started",
    },
    levelOfEffort: "X-Large",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.e465psrtiewl#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.portfolioViews,
  },
  {
    id: "6",
    name: "Interaction Model Update",
    description: "Modernized interaction patterns for touch, keyboard, and accessibility",
    ownerValue: "Medium",
    platformReadiness: "Medium",
    businessValue: "Low",
    dependencies: "High",
    dependencyTeams: ["UIF"],
    tier: "Enhancement",
    risks: ["Regression in existing tools"],
    assumptions: ["Design system supports new patterns"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "C",
      UIF: "R",
      Hubs: "I",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-02-15",
      endDate: "2026-04-30",
      status: "Not Started",
    },
    levelOfEffort: "Small",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.lxtna1ufykz#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.interactionModel,
  },
  {
    id: "7",
    name: "Stage-Based Workflows",
    description: "Project lifecycle stages with automated triggers and milestone tracking",
    ownerValue: "Medium",
    platformReadiness: "Medium",
    businessValue: "High",
    dependencies: "Low",
    dependencyTeams: ["Platform", "Hubs", "Connect"],
    tier: "Extension",
    risks: ["Integration with existing workflows", "Customization requirements"],
    assumptions: ["Standard stages can be defined", "Automation engine is available"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "C",
      Hubs: "C",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-07-01",
      endDate: "2027-02-28",
      status: "Not Started",
    },
    levelOfEffort: "Large",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.ancclqvg06n8#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.stageBasedWorkflows,
  },
  {
    id: "8",
    name: "Universal Controls - Compare",
    description: "Side-by-side comparison capabilities across projects and time periods",
    ownerValue: "Medium",
    platformReadiness: "Medium",
    businessValue: "Medium",
    dependencies: "Low",
    dependencyTeams: ["UIF", "Platform"],
    tier: "Net New",
    risks: ["UI complexity", "Data synchronization"],
    assumptions: ["Comparable data structures exist"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "C",
      Hubs: "I",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "C",
    },
    timeline: {
      startDate: "2026-08-01",
      endDate: "2026-11-30",
      status: "Not Started",
    },
    levelOfEffort: "Large",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.4dasw04wed4s#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.ucCompare,
  },
  {
    id: "9",
    name: "Universal Controls - AI Summary",
    description: "AI-generated summaries and insights for projects and portfolios",
    ownerValue: "Medium",
    platformReadiness: "Medium",
    businessValue: "Medium",
    dependencies: "High",
    dependencyTeams: ["Platform", "Hubs"],
    tier: "Enhancement",
    risks: ["AI accuracy concerns", "Cost management"],
    assumptions: ["AI infrastructure is available", "Users trust AI-generated content"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "C",
      Hubs: "C",
      "Procore Connect": null,
      Assist: "C",
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-09-01",
      endDate: "2027-03-31",
      status: "Not Started",
    },
    levelOfEffort: "Medium",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.greokqwyrtnb#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.aiSummary,
  },
  {
    id: "10",
    name: "Universal Controls - View Modes",
    description: "Flexible view modes including list, grid, timeline, and map views",
    ownerValue: "Low",
    platformReadiness: "High",
    businessValue: "Low",
    dependencies: "Low",
    dependencyTeams: ["UIF"],
    tier: "Extension",
    risks: ["Maintenance burden across views"],
    assumptions: ["Users need multiple view options"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "R",
      UIF: "C",
      Hubs: "I",
      "Procore Connect": null,
      Assist: null,
      "Tool Teams": "C",
    },
    timeline: {
      startDate: "2026-05-01",
      endDate: "2026-07-31",
      status: "Not Started",
    },
    levelOfEffort: "Small",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.csq11c6en4qo#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.ucViewModes,
  },
  {
    id: "11",
    name: "Procore Connect for Owners",
    description: "External integrations and data connections tailored for owner needs",
    ownerValue: "High",
    platformReadiness: "High",
    businessValue: "Medium",
    dependencies: "High",
    dependencyTeams: ["Connect", "Platform"],
    tier: "Enhancement",
    risks: ["Third-party API stability", "Security requirements"],
    assumptions: ["Key integrations are identified", "Connect platform supports new patterns"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "C",
      UIF: "C",
      Hubs: "I",
      "Procore Connect": "R",
      Assist: null,
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2026-10-01",
      endDate: "2027-04-30",
      status: "Not Started",
    },
    levelOfEffort: "Medium",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.y5196099g888#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.procoreConnect,
  },
  {
    id: "12",
    name: "Portfolio Level Assist",
    description: "AI-powered assistant for portfolio-level questions and actions",
    ownerValue: "Medium",
    platformReadiness: "Low",
    businessValue: "Medium",
    dependencies: "High",
    dependencyTeams: ["Platform", "Hubs", "Connect"],
    tier: "Extension",
    risks: ["AI reliability", "Action authorization"],
    assumptions: ["AI can access portfolio data", "User permissions are well-defined"],
    raci: {
      "Owner Strat": "A",
      "Owner Team": "C",
      UIF: "C",
      Hubs: null,
      "Procore Connect": null,
      Assist: "R",
      "Tool Teams": "I",
    },
    timeline: {
      startDate: "2027-01-01",
      endDate: "2027-08-31",
      status: "Not Started",
    },
    levelOfEffort: "X-Large",
    links: {
      onePager:
        "https://docs.google.com/document/d/1aOOe95D-NqdK3jWC7EL8bkih6teZI3KKYPsOihSIpEg/edit?tab=t.x4zbs1wgdwnp#heading=h.f8m01zzbtknq",
      figma: FIGMA_URL,
      prototype: PROTOTYPE_URL,
    },
    thumbnail: IMAGES.aiAssist,
  },
]
